apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webgame-collection
  namespace: webgame-collection
spec:
  rules:
    - host: games.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webgame-collection
                port:
                  number: 80
